// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_HelloWorldQtQuick();
Q_GHS_KEEP_REFERENCE(qml_register_types_HelloWorldQtQuick)

class HelloWorldQtQuickPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    HelloWorldQtQuickPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_HelloWorldQtQuick;
        Q_UNUSED(registration)
    }
};



#include "HelloWorldQtQuickplugin_HelloWorldQtQuickPlugin.moc"
